# Generated by Django 5.0.6 on 2024-06-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
