# Generated by Django 5.0.6 on 2024-06-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.FileField(default=2, upload_to='files'),
            preserve_default=False,
        ),
    ]
